#ifdef MAIN
MESSAGE gen[] = {

  {  0,0,"Marduk the explorer discovered the continent of Halkanar long ages in the past." },
  {  0,0,"When he landed he found there were no humans as indigenous people." },
  {  0,0,"Instead halkanar was primarily settled by dwarves and elves." },
  {  0,0,"At this time there was much wildlife living in Halkanar." },
  {  0,0,"Unicorns were very abundant in Halkanar at this time." },
  {  0,0,"Marduk had decided to build his city on the shores of what is now Marduk Lake." },
  {  0,0,"From here men spread out and settled the cities of Larkon, Solat, Alukrahn, Aljan, Algamar and Talgon." },
  {  0,0,"Men lived in peace with the elves and dwarves and Halkanar grew rich." },
  {  0,0,"This attracted the attention of the dark wizards and they began to come to Halkanar." },
  {  0,0,"The first of these was Caldnar.  He brought many fell monsters with him and conqureed the land." },
  {  0,0,"The elves began to hide themselves in the forests and the dwarves hid under the mountains." },
  {  0,0,"Men having nowhere they could go were enslaved by Caldnar." },
  {  0,0,"Caldnar had a new capital city built it in the Kobold Mountains and built his castle in the Northern Realm." },
  {  0,0,"Caldnar was always surrounded by powerful magic and nobody could defeat him." },
  {  0,0,"He ruled Halkanar with an iron fist for almost 20 years." },
  {  0,0,"When the 2nd of the dark wizards arrived, Elanther." },
  {  0,0,"Elanther was much stronger than Caldnar and it took little effort to destory him." },
  {  0,0,"For all of Elanther's power he appeared to be in constant fear of some greater power." },
  {  0,0,"So he began to build temples all over Halkanar where bizarre rituls were held." },
  {  0,0,"Elanther was constantly looking for a greater power and he believed it was held by the Unicorns." },
  {  0,0,"Therefore the followers of Elanther began to capture the Unicorns and sacrifice them in the temples." },
  {  0,0,"The Unicorns became scarce and the ones that survived fled to a hidden valley to escape Elanther." },
  {  0,0,"Elanther built the complex at Arath Ma Kon and begon working on a powerful magic." },
  {  0,0,"While Elanther was hidden away at Arath Ma Kon, the last and most fearful of the dark wizards arrived, Eshter." },
  {  0,0,"Eshter found Elanther at Arath Ma Kon and they battled for many days before Elanther fled." },
  {  0,0,"He fled to the enchanted lands and used his magic to create the Ring Ridges and placed a magic upon them to hide them." },
  {  0,0,"With his last project interrupted by Esther, Elanther began a new more powerful magic." },
  {  0,0,"Elanther found Adamantite in the Enchanted lands and used it to forge his new magic." },
  {  0,0,"But Eshter had found him before he was ready and battle between them began a new." },
  {  0,0,"Much of Halkanar was laid waste during the war between Eshter and Elanther." },
  {  0,0,"Eventually Eshter defeated Elanther and laid claim to all of Halkanar." },
  {  0,0,"She would rule Halkanar for 4 years before the coming the great white wizard." },
  {  0,0,"He came from somewhere over the sea and gave no name, the people called him Nichor." },
  {  0,0,"Nichor built his base in the northern portion of the Kobold Mountains and began to wage war against Eshter." },
  {  0,0,"Eshter was no match for Nichor and was forced back." },
  {  0,0,"Knowing that she was lost she ensnared the last of the Unicorns and disappeared." },
  {  0,0,"Nobody knows where she went, but they do know that she was not destroyed." },
  {  0,0,"After the disappearence of Eshter, men began to multiply in the land again." },
  {  0,0,"The dangerous monstesr that had plagued the land had hidden themselves away." },
  {  0,0,"At this time the cities of Talfharin, New Solat, Goldville, and Radon were settled." },
  {  0,0,"Through Nichor's aid Halkanar recovered from the ravages of the Dark Wizards." },
  {  0,0,"Peace was again found in Halkanar for many long years." },
  {  0,0,"But now a new darkness is forming and horrors are again walking the earth." },




  {  0,0,"The Island of Halkanar was settled long ages in the past" },
  {  0,0,"The Radon river flows from Radon to Marduk Vale" },
  {  0,0,"The Anjar River is located north of the Enchanted Lands" },
  {  0,0,"The ruins of Larkon are found at the Head of the Anjar River" },
  {  0,0,"The Ring Ridges are found in the Enchanted Lands" },
  {  0,0,"Elanthers Forge is lacated inside the Ring Ridges" },
  {  0,0,"Lake Quenar is located inside the Ring Ridges" },
  {  0,0,"Solat was once the capital of the Old Realm but is now only ruins" },
  {  0,0,"Alukrahn was once a powerfull city in the Northern Realm" },
  {  0,0,"The Coastal mountains are located west of the Great Desert" },
  {  0,0,"The Great River flows through the northern half of Halkanar" },
  {  0,0,"Caldnar once built a castle in the Northern Realm" },
  {  0,0,"Rumors speak of a Triad of Might" },
  {  0,0,"The Golden Mountains lie north of the Great Desert" },
  {  0,0,"The North Forest lies north of the Golden Mountains" },
  {  0,0,"Volcanic Lake is in the Kobold Mountains between the Middle and East passes" },
  {  0,0,"Marduk Lake is the middle of Halkanar" },
  {  0,0,"The Anjar Mountains lie south of the Anjar River and north of the Enchanted Lands" },
  {  0,0,"The Larkon Mountains run from Larkon lake north to Marduk Lake" },

  {  0,0,"Goldville is located in the Coastal mountains halfway up the Desert" },
  {  0,0,"New South Radon is located on the south west shore of Radon Lake" },
  {  0,0,"The great city of Radon can be found on the north of Radon Lake" },
  {  0,0,"Talfharin is on the banks of the Great River in the Northern Realm" },
  {  0,0,"New Solat is located on the north shore of Marduk Lake" },
  {  0,0,"Marduk is on the south shore of Marduk Lake" },
  {  0,0,"Marduk is the capital city of Halkanar" },

  {  0,0,"The Major realms of Halkanar are as follows:" },
  {  0,0,"The Northern Realm lies north of the Great Desert and West of the Realm of Nichor" },
  {  0,0,"The Realm of Nichor lies east of the Northern Realm, west of The Olde Realm  and North of The Kobold Mountains" },
  {  0,0,"The Olde Realm lies east of the Realm of Nichor, West of the Northeast Wastes and north of The Realm of Marduk" },
  {  0,0,"The Northeast Wastes lie east of The Olde Realm and north of The Realm of Larkon" },
  {  0,0,"The Great Desert lies west of the Kobold Mountains, South of the Northern Realm and north of The Radon Valley" },
  {  0,0,"The Kobold Mountains lie east of The Great Desert, west of The Realm of Marduk, south of the Realm of Nichor and north of The Realm of Talgon" },
  {  0,0,"The Realm of Marduk lies east of the Kobold Mountains, west of The Realm of Larkon, south of The Olde Realm and north of The Enchanted Lands" },
  {  0,0,"The Realm of Larkon lies east of The Realm of Marduk, south of The Northeast Wastes and north of The Valley of the Unicorns" },
  {  0,0,"The Radon Valley lies west of the Realm of Talgon and south of The Great Desert" },
  {  0,0,"The Realm of Talgon lies east of The Radon Valley, west of The Enchanged Lands and south of the Kobold Mountains" },
  {  0,0,"The Enchanted Lands lie east of The Realm of Talgon, west of The Valley of the Unicorns and south of The Realm of Marduk" },
  {  0,0,"The Valley of the Unicorns lies east of the Enchanted Lands and south of The Realm of Larkon" },

  {  0,1,"The Ruins of Castle Caldnar can be found at the end of the Talfharin Forest" },
  {  0,1,"The Talfharin forest starts across the river from Talfharin" },
  {  0,1,"Horror point lies at the North-West most point of Halkanar" },
  {  0,1,"The Temple of the Forest lies in the North Forests" },
  {  0,1,"The Ruins of Alukrahn are on the bank of the Great River" },

  {  0,2,"The Alakahri Forest is north of the Great River" },
  {  0,2,"The Alakahri Butte is in the middle of the Alakahri Forest" },
  {  0,2,"Castle Alakahri is on the top of the Alakahri Butte" },
  {  0,2,"The Temple of the North is located off the Middle pass just south of the river" },
  {  0,2,"The Ruins of Aljan are located off the western mountain pass" },
  {  0,2,"The Stronghold of the Orcs is in a valley between the Middle and East passes" },

  {  0,3,"The Ruins of Solat are just north and west of New Solat" },
  {  0,3,"The ruins of Castle Tralin are just north and east of New Solat" },
  {  0,3,"The Den of the Dragon is located in the North East corner of the Olde Realm" },
  {  0,3,"The Isle of the Dead is near the south shore of Marduk Lake" },
  {  0,3,"The Haunted Isle if near the west shore of Marduk Lake" },
  {  0,3,"The Temple of the Water is on an Island near the East shore of Marduk Lake" },

  {  0,4,"The Great swamp is located south of the Great river" },
  {  0,4,"There is a cave in the middle of the Great Swamp" },
  {  0,4,"The Olde Forest lies all along the north of the Great River" },
  {  0,4,"There is a cave in the East of the Olde Forest" },
  {  0,4,"Lamia point is in the Forest south of the Great Swamp" },
  {  0,4,"The Trolls Den is on the west edge of the Larkon Mountains" },

  {  0,5,"The Temple of the Crescent is in a Crescent shaped mountain" },
  {  0,5,"The Temple of the Sun is located in the south portion of the Desert" },
  {  0,5,"There are some old mines in the hills just south of Goldville" },
  {  0,5,"Areth Knoll is located in a valley in the Coastal Mountains" },

  {  0,6,"There are three main passes in the Kobold Mountains" },
  {  0,6,"The Den of Horror is located off the West pass, near the north" },
  {  0,6,"The Temple of the Dark is on the West edge of the Kobold Range" },
  {  0,6,"The Algamar ruins are located in the Foothills of the Kobold Mountains" },
  {  0,6,"The Lost Mine is located off the West pass, South of the Den of Horror" },
  {  0,6,"The Den of the Beast is at the Southern edge of the Middle Pass" },
  {  0,6,"Arath Ma Kon is located on the Middle pass northwest of Den of the Beast" },
  {  0,6,"The Hall of the Kobold Lords is just north of Volcanic Lake" },
  {  0,6,"The Ruins of Caldnar are located of the east pass" },
  {  0,6,"The Temple of the Moon is located of the East pass, North of Caldnar" },

  {  0,7,"There are three passes running along the Anjar Mountains" },
  {  0,7,"The Isle of the Will-o-Wisps is in the Radon river south of the Anjar river" },
  {  0,7,"The Tomb of Caldnar lies due East from the Isle of the Will-o-Wisps" },
  {  0,7,"The Black Hole between the Middle and North passes, not far from the Radon River" },
  {  0,7,"The Hall of the Giants lies south of Marduk at the Edge of the Kobold Mountains" },
  {  0,7,"The Lost Tomb lis near Dryad Lake" },
  {  0,7,"Dryad Lake is located in the Anjar mountains between the North and Middle passes" },
  {  0,7,"The Cave of Enchantment lies between the Middle and South passes" },
  {  0,7,"The Valley of fear is located along a canyon connected with the south pass" },
  {  0,7,"A pass into the Anjar mountains exists east of Larkon" },
  {  0,7,"The Valley of the Gods is between the North and middle Passes south of Larkon" },
  {  0,7,"The Valley of the Giants is between the North and middle passes" },
  {  0,7,"The Valley of the Titans is between the South and middle passes" },

  {  0,9,"Radon is the one of the youngest city in all the Realm of Halkanar" },
  {  0,9,"There are only two routes in or out of the Radon valley" },
  {  0,9,"One of the routes out of radon is the Merchants Highway" },
  {  0,9,"The easiest way out of Radon is the Radon River" },
  {  0,9,"There exists an old mine due north of Radon" },
  {  0,9,"There is an old mine due west of New South Radon" },
  {  0,9,"There is an Island off the tip of Radon Peninsula" },

  {  0,10,"A pass goes into the Radon mountains just north of the Radon River" },
  {  0,10,"Gargoyle Peak is in the Radon mountains at the end of a pass" },
  {  0,10,"A pass goes into the Kobold Mountains just north of the Radon River" },
  {  0,10,"Calton peak is in the Kobold mountains at the end of a pass" },
  {  0,10,"The Goblin Caves are located just off the Calton Peak pass" },
  {  0,10,"The Lost valley lies off the Gargoyle Peak pass" },
  {  0,10,"The Temple of the South lies in the South Kobold Mountains" },
  {  0,10,"A pass goes in the South Kobold Mountains south of Talgon" },
  {  0,10,"The Valley of Blood lies in the South Radon Mountains" },
  {  0,10,"The only pass into the South Radon range is on the Coast" },

  {  0,11,"The Ring Ridges lie near the South Eastern corner of the Enchanted lands" },
  {  0,11,"Lone Peak was once part of the Ring Ridges" },
  {  0,11,"Lone Peak is on the western side of the Ring Ridges" },
  {  0,11,"The Moon Hills lie north of the Ring Ridges" },
  {  0,11,"The Den of the Dragons lie in the Moon Hills" },
  {  0,11,"The Swamp of the Souls lies near the bend of the Radon River" },
  {  0,11,"The Cave of Souls is in the middle of the Swamp of the Souls" },
  {  0,11,"The Wisp desert lies just south of the Anjar mountains" },
  {  0,11,"The Cave of the Wisps is in the Wisp Desert" },
  {  0,11,"The Gates of Hell are in the Canyon at the Southeast edge of the Enchanted Lands" },
  {  0,11,"The Throne of the Gods is located in the Southron Mountain Range" },
  {  0,11,"The Anjar desert lies south of the Anjar Mountains east of the Enchanted Lands" },
  {  0,11,"The entrance to the Earth Wound is in the Anjar Desert" },

  { 999,99,"EOL" }
  };

#else

extern MESSAGE gen[];

#endif

