#ifdef MAIN
MESSAGE lore[] = {
  { 0,0,"This message intentionally left blank" },
  { 0,0,"Few have searched for the gateway, None have ever returned" },
  { 0,5,"Three items are needed to enter the Gateway" },
  { 0,7,"The Talisman is needed to find the Gateway" },
  { 0,2,"The Aurafax is needed to activate the Gateway" },
  { 0,8,"The Amulet of Yathun is needed to enter the Gateway" },
  { 0,0,"Rumors say a Gateway exists from our plane to the Realm of Eshter" },
  { 0,7,"It is said that Esther holds the secret of the Unicorn" },
  { 0,0,"The Unicorns disappeared long ago Some say they are only a myth" },
  { 0,0,"Only Legends know the truth of the Unicorn" },
  { 0,6,"Elanther was the builder of the Talning rod" },
  { 0,6,"The followers of Elanther Built the Temples" },
  { 0,6,"The Talning rod is said to lie at the bottom of Arath Ma Kon" },
  { 0,6,"Long ago Elanther disappeared into the East" },
  { 0,7,"It was Elanther who built the Ring Ridges" },
  { 0,7,"It was at Elanthers Forge that Elanther met his final defeat" },
  { 0,7,"Lake Quenar was built by Elanther" },
  { 0,8,"Larkon was destroyed during the Caldnar Droughts" },
  { 0,8,"Larkon was once a major city" },
  { 0,8,"It was the Will o Wisps that drove away the people of Larkon" },
  { 0,2,"The Amulet of Yathun was last seen in Larkon" },
  { 0,2,"The Talisman was last in the possession of Elanther" },
  { 0,2,"The Aurafax was last seen in the possession of Caldnar" },
  { 0,0,"The city of Nichorville contains the greatest knowledge of lore" },
  { 0,7,"Nichorville lies in the Kobold Mountains west of Marduk" },
  { 0,7,"Caldnar was a mighty wizard in the past" },
  { 0,7,"Caldnars last known location was in the Norhtern Realm" },
  { 0,2,"Caldnar once dwealt in the Enchanted Lands" },
  { 0,2,"Some believe that Eshter was the daughter of Caldnar" },
  { 0,0,"The Old Realm is located north of Marduk Lake" },
  { 0,2,"A Great sword once existed somewhere in the Old Realm" },
  { 0,2,"An Unspeakable horror lives at the bottom of the Den of Horrors" },
  { 0,2,"A Mystical traveling machine is rumored to be in the Den of Horrors" },
  { 0,6,"Some say the Temples will reveal the secrets of the Talning Rod" },
  { 0,0,"Few now living know the location of the Valley of the Unicorns" },
  { 0,12,"It was Eshter who removed the unicorns from the Valley" },
  { 0,12,"After Eshter caputured the unicorns she fled through the Gateway" },
  { 0,12,"The Gateway can be found on a small Island east of Halkanar" },
  { 0,2,"The last Crown of Might was last seen in Solat" },
  { 0,2,"A strange Mystical sword was once lost in Areth Knoll" },
  { 0,6,"The Dwarvish axe was lost in the Lost Mines of the dwarves" },
  { 0,6,"A powerfull sword exist somewhere in the ruins of Caldnar" },
  { 0,2,"The last Sceptre of Might was in the city Alukrahn" },
  { 0,7,"Caldnar possessed a mystical light weapon" },
  { 0,7,"Caldnars mystical weapon is rumored to be in his tomb" },
  { 0,2,"Alakahri possessed a strange mystical picture machine" },
  { 0,2,"The picture machine only works at the bottoms of dungeons" },
  { 0,11,"A strange machine can be found under Lone Peak" },
  { 0,11,"Lone Peak was originally made be Elanther" },
  { 0,7,"The Orb of Might is said to be in the Black Hole" },
  { 0,0,"The Triad of might consisted of a Crown, a Sceptre, and an Orb" },
  { 0,0,"All three pieces of the Triad must be owned for the power to work" },
  { 0,0,"Elanther had temples built over most of Halkanar" },
  { 0,0,"It is said that Areth Knoll was created by Caldnar" },
  { 0,0,"Arath Ma Kon was built by Elanther" },

  { L_014,90,"The Talning rod has eight different functions" },
  { L_015,90,"Words of Power can be found at the bottoms of some dungeons" },
  { L_016,90,"\"Mintaal\" will return you to the Surface" },
  { L_017,90,"\"Auralal\" on the Talning rod produces Clairaudience" },
  { L_018,90,"\"Loeer\" on the Talning rod will allow the understanding of lore" },
  { L_036,90,"A mysterious object came out of the sky at Areth Knoll long ago" },
  { L_012,90,"\"Reahl\" on the Talning rod will allow the understanding of Languages" },
  { L_013,90,"\"Litraal\" on the Talning rod will produce light" },
  { L_001,90,"\"Mala\" on the Talning rod will detect magic" },
  { L_002,90,"The opposite of returning to the surface, is to go to the bottom" },
  { L_003,90,"\"Idahl\" on the Talning rod will identify an enemy" },
  { L_004,90,"\"Ilital\" will transport you one level up" },
  { L_005,90,"The opposite of going one level up, is to go one level down" },
  { L_006,90,"The Triad of Might has wonderous power!" },
  { L_007,90,"\"Suraal\" on the Talning rod will return you to the surface" },
  { L_019,90,"Beware the dangers beyond the Gateway" },
  { L_020,90,"The Valley of the Unicorns can only be found by riding a Pegasus" },
  { L_021,90,"\"Indral\" will slow poison" },
  { L_022,90,"\"Oraclal\" will perform Clairaudience" },
  { L_023,90,"use \"Illumina\" if you are in the dark" },
  { L_030,90,"The Talismans secondary use is Identification" },
  { L_031,90,"\"Auraral\" will summon an Aerial Servent" },
  { L_032,90,"Cautious use of \"Manatal\" can increase mana" },
  { L_033,90,"\"Hurar\" might speed you up" },
  { L_034,90,"\"Visorae\" can enlighten you about your surroundings" },
  { L_024,90,"Words of power cannot be used while in combat" },
  { L_025,90,"Beware, sometimes words of power backfire!" },
  { L_026,90,"Afraid of your enemies? Try \"Fearaway\"" },
  { L_027,90,"Some words of power may have side effects, be cautious" },
  { L_028,90,"\"Detral\" on the Talning rod will find all traps on a level" },
  { L_029,90,"Try using \"Blinkahl\" to escape your enemies" },
  { L_008,90,"Words of power generally do not work with enemies about" },
  { L_009,90,"You can find valuable Manuals in some valleys" },
  { L_010,90,"Bet you thought you would find something usefull down here, signed Elanther" },
  { L_011,90,"The Triad of Might can defeat Eshter" },
  { L_035,90,"Remember to wear the Amulet of Yathun before entering the Gateway" },

  {  0,0,"Recipe: Amulet of Fire Protection\nCraft Item:\nPliers\n\nIngredients:\nNecklace of nothing\nSmall Ruby\nMedium Ruby\nLarge Ruby\nHuge Ruby" },
  {  0,0,"Recipe: Mithril Crossbow\nCraft Item:\nAnvil\n\nIngredients:\nMithril Bar\n2 x Wood\n" },
  {  0,0,"Recipe: Flamesword\nCraft Item:\nAnvil\n\nIngredients:\nGreatsword\nMithril Bar\n8 x Potion of Fire Water\n" },
  {  0,0,"Recipe: Ring of Food Detection\nCraft Item:\nPliers\n\nIngredients:\nRing of Nothing\nLarge Emerald\nIron Rations" },
  {  0,0,"Recipe: Ring of Up Detection\nCraft Item:\nPliers\n\nIngredients:\nRing of Nothing\nHuge Amber\nScroll of Object Detection" },
  {  0,0,"Recipe: Ring of Down Detection\nCraft Item:\nPliers\n\nIngredients:\nRing of Nothing\nHuge Amethyst\nScroll of Object Detection" },
  {  0,0,"Recipe: Sunsword\nCraft Item:\nAnvil\n\nIngredients:\nFlameSword\nExcalibur\nHuge Pearl\nJewel of Attacks\nScroll of the Sun" },
  {  0,0,"Recipe: Ring of Experience Gain\nCraft Item:\nPliers\n\nIngredients:\nRing of Nothing\nSmall Pearl\nSmall Black Pearl\nBook of Experience Gain 5%" },
  {  0,0,"Recipe: Golden Shield\nCraft Item:\nAnvil\nIngredients:\nLarge Iron Shield\nGold Bar" },
  {  0,0,"Recipe: Mithril Shield\nCraft Item:\nAnvil\nIngredients:\nLarge Iron Shield\nMithril Bar" },
  {  0,0,"Recipe: Golden Helm\nCraft Item:\nAnvil\nIngredients:\nHelm\nGold Bar" },
  {  0,0,"Recipe: Mithril Helm\nCraft Item:\nAnvil\nIngredients:\nHelm\nMithril Bar" },
  {  0,0,"Recipe: Mithril Bar\nCraft Item:\nAnvil\nIngredients:\n10 x Mithril Ore" },
  {  0,0,"Recipe: Gold Bar\nCraft Item:\nAnvil\nIngredients:\n10 x Gold Ore" },
  {  0,0,"Recipe: Silver Bar\nCraft Item:\nAnvil\nIngredients:\n10 x Silver Ore" },
  {  0,0,"Recipe: Copper Bar\nCraft Item:\nAnvil\nIngredients:\n10 x Copper Ore" },
  {  0,0,"Recipe: White Gold Bar\nCraft Item:\nAnvil\nIngredients:\nGold Bar\nSilver Bar" },
  {  0,0,"Recipe: Potion of Cure Poison\nCraft Item:\nHot Plate\nIngredients:\n2 x Potion of Slow Poison" },
  {  0,0,"Recipe: Potion of Healing\nCraft Item:\nHot Plate\nIngredients:\nWater\n4 x Bottle of Salve" },
  {  0,0,"Recipe: Potion of Xtra Healing\nCraft Item:\nHot Plate\nIngredients:\nWater\n4 x Bottle of Wound Healer" },
  {  0,0,"Recipe: Potion of Super Healing\nCraft Item:\nHot Plate\nIngredients:\nWater\n2 x Potion of Xtra Healing" },
  {  0,0,"Recipe: Potion of Miracle Healing\nCraft Item:\nHot Plate\nIngredients:\nWater\n2 x Potion of Super Healing" },
  {  0,0,"Recipe: Mahrkaaf Solution\nCraft Item:\nHot Plate\nIngredients:\nWater\n2 x Potion of Miracle Healing" },
  {  0,0,"Recipe: Potion of Cureall\nCraft Item:\nHot Plate\nIngredients:\nWater\nPotion of Healing\nPotion of Clear Headedness\nPotion of Bravery\nPotion of Sight\nPotion of Cure Poison" },
  {  0,0,"Recipe: Potion of Sight\nCraft Item:\nHot Plate\nIngredients:\nWater\nPotion of Blindness\nBottle of Salve" },
  {  0,0,"Recipe: Potion of Bravery\nCraft Item:\nHot Plate\nIngredients:\nWater\nPotion of Fear\nBottle of Salve" },
  {  0,0,"Recipe: Potion of Clear Headedness\nCraft Item:\nHot Plate\nIngredients:\nWater\nPotion of Confusion\nBottle of Salve" },
  {  0,0,"Recipe: Scroll of Enchant Weapon\nCraft Item:\nQuill\nIngredients:\nScroll of Blank Paper\nInk\nWeapon Powder\nHoly Water" },
  {  0,0,"Recipe: Weapon Powder\nCraft Item:\nAnvil\nIngredients:\nDagger\nBroadsword\nLong Bow\nHeavy Crossbow\nBardiche\nWhite Gold Bar\nHorn of Blasting" },
  {  0,0,"Recipe: Scroll of Enchant Armour\nCraft Item:\nQuill\nIngredients:\nScroll of Blank Paper\nInk\nArmour Powder\nHoly Water" },
  {  0,0,"Recipe: Armour Powder\nCraft Item:\nAnvil\nIngredients:Large Iron Shield\nPlatemail\nHigh Iron Boots\nHelm\nWhite Gold Bar\nHorn of Blasting" },
  {  0,0,"Recipe: Protein Shake\nCraft Item:\nHot Plate\nIngredients:\nWater\nMilk\nMeat\nEgg\nCheese" },
  {  0,0,"Recipe: Fruit Punch\nCraft Item:\nHot Plate\nIngredients:\nWater\nApple\nLemon\nLime\nCherry" },
  {  0,0,"Recipe: Vegitable Juice\nCraft Item:\nHot Plate\nIngredients:\nWater\nAsparagus\nTomato\nOnion\nGreen Bell Pepper" },
  {  0,0,"Recipe: Potion of Health\nCraft Item:\nHot Plate\nIngredients:\nWater\nProtein Shake\nFruit Punch\nVegitable Juice" },
  {  0,0,"Recipe: Potion of Extra Health\nCraft Item:\nHot Plate\nIngredients:\nWater\n2 x Potion of Health" },
  {  0,0,"Recipe: Potion of Fitness\nCraft Item:\nHot Plate\nIngredients:\nWater\n2 x Potion of Extra Health" },
  {  0,0,"Recipe: Potion of Extra Fitness\nCraft Item:\nHot Plate\nIngredients:\nWater\n2 x Potion of Fitness" },
  {  0,0,"Recipe: Potion of Haleness\nCraft Item:\nHot Plate\nIngredients:\nWater\n2 x Potion of Extra Fitness" },
  {  0,0,"Recipe: Ring of Nourishment\nCraft Item:\nPliers\nIngredients:\nRing of Nothing\nHuge Emerald\nHuge Ruby\nHuge Saphire\n2 x Potion of Haleness" },
  {  0,0,"Recipe: Pepper Spray\nCraft Item:\nHot Plate\nIngredients:\nWater\nGreen Bell Pepper\nRed Bell Pepper\nYellow Bell Pepper" },
  {  0,0,"Recipe: Platemail of the Archmagi\nCraft Item:\nAnvil\nIngredients:\nPlatemail\nRobe of the Archmagi\nScroll of Enchant Armour" },
  {  0,0,"Recipe: Robe of Invincibility\nCraft Item:\nEnchanted Needle\nIngredients:\nRobe of White\nDiamondskin\nScroll of Protection\nScroll of Bless" },
  {  0,0,"Recipe: Poison Spear\nCraft Item:\nNone\nIngredients:\nSpear\nPotion of Poison" },
  {  0,0,"Recipe: Poison Dagger\nCraft Item:\nNone\nIngredients:\nDagger\nPotion of Poison" },
  {  0,0,"Recipe: Poison Blade\nCraft Item:\nNone\nIngredients:\nLong Sword\nPotion of Poison" },
  {  0,0,"Recipe: Robe of Many Colors\nCraft Item:\nEnchanted Needle\nIngredients:\nRobe of Red\nRobe of Green\nRobe of Blue" },
  {  0,0,"Recipe: Robe of White\nCraft Item:\nEnchanted Needle\nIngredients:\nRobe of Many Colors\n4 x Holy Water" },
  {  0,0,"Recipe: Holy Water\nCraft Item:\nHot Plate\nIngredients:\nWater\nScroll of Bless" },
  {  0,0,"Recipe: Honey Milk\nCraft Item:\nHot Plate\nIngredients:\nMilk\nHoney" },
  {  0,0,"Recipe: Bread\nCraft Item:\nHot Plate\nIngredients:\nWater\nFlour" },
  {  0,0,"Recipe: S.O.S.\nCraft Item:\nHot Plate\nIngredients:\nMeat\nPotato\nMilk\nFlour\nButter" },
  {  0,0,"Recipe: Stew\nCraft Item:\nHot Plate\nIngredients:\nMeat\nPotato\nOnion\nMushroom\nFlour\nWater" },
  {  0,0,"Recipe: Steak Dinner\nCraft Item:\nHot Plate\nIngredients:\nMeat\nPotato\nButter\nAsparagus\nMushroom\nSalt\nCheese" },
  {  0,0,"Recipe: Ring of Levitation\nCraft Item:\nPliers\n\nIngredients:\nRing of Nothing\nMedium Saphire\nPotion of Levitation" },
  {  0,0,"Recipe: Broom of Flying\nCraft Item:\nNone\n\nIngredients:\nBroom\nPotion of Levitation\nPotion of Haste\nScroll of Bless" },

  { 999,99,"EOL" },
  };

#else

extern MESSAGE lore[];

#endif

